name: Build LaTeX document

on:
  push:
    paths:
      - 'resume.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up TeX Live
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex

      - name: Compile LaTeX document
        run: latexmk -pdf -interaction=nonstopmode resume.tex

      - name: Rename and move PDF
        run: mv resume.pdf index.pdf

      - name: Commit and push PDF
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.pdf
          git commit -m "Update compiled resume PDF"
          git push